### ISSUE TITLE
3GPP library

### ISSUE THREAD

**Issue by loboris** [pycom/pycom-micropython-sigfox#107]
I'm glad you are using my [libGSM](https://github.com/loboris/ESP32-PPPOS-EXAMPLE/tree/master/components/pppos) as your **lib3GPP**.
It is free to use, but it is common practice to mention the original source of the code.

**Comment by danicampora** [comment]
@loboris you are absolutely right. That was clearly an oversight from our side. We'll fix ti right away.

**Comment by loboris** [comment]
Thanks, and congratulations on the excellent work you've done.
