### ISSUE TITLE
Pymakr unable to install in Atom 

### ISSUE THREAD

**Issue by liowmei** [pycom/pycom-micropython-sigfox#152]
Hi there, i am still unable to install the Pymakr 1.2.10 in the Atom version of 1.25.0. It show me failed to search for the package where stated there " connect ETIMEOUT "50.16.223.157.443".  How can i solve this problem? Thank you 

os : windows 8.1x64
Atom 1.25.0
Pymakr 1.2.10

**Comment by sdaniel55** [comment]
HI @liowmei 
I'll close this issue for now. If you're still having problems, please open an issue in [pycom/pymakr-atom](https://github.com/pycom/pymakr-atom)
