### ISSUE TITLE
FiPy with Pytrack gives error on load module

### ISSUE THREAD

**Issue by tanmoydutta** [pycom/pycom-micropython-sigfox#159]
**PYB: soft reboot
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "Pytrack/Pytrack.py", line 5, in <module>
TypeError: cannot create 'module' instances
MicroPython 2ac6da2 on 2017-12-18; FiPy with ESP32
Type "help()" for more information.
>>> import os
>>> os.uname()
(sysname='FiPy', nodename='FiPy', release='1.11.0.b1', version='2ac6da2 on 2017-12-18', machine='FiPy with ESP32', lorawan='1.0.0')
>>> os.listdir('lib/pycoproc')
['pycoproc.py']
>>> os.listdir()
['lib', 'boot.py', 'main.py', 'project.pymakr', 'sys', 'cert', 'L76GNSS', 'Pytrack', 'LIS2HH12.py']
>>> os.listdir('Pytrack')
['pytrack.py']
>>> os.listdir('lib/pycoproc')
['pycoproc.py']
>>>**

Trying to make the Pytrack to work wth the FiPy but keep getting the following error - 
>>> import machine
>>> machine.reset()
ets Jun  8 2016 00:22:57

rst:0x7 (TG0WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff9028,len:8
load:0x3fff9030,len:1060
load:0x4009fa00,len:0
ho 12 tail 0 room 4
load:0x4009fa00,len:15160
entry 0x400a0644
**Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "Pytrack/Pytrack.py", line 5, in <module>
TypeError: cannot create 'module' instances**
MicroPython 2ac6da2 on 2017-12-18; FiPy with ESP32
Type "help()" for more information.
>>>

The Pytrack works fine with a LoPy except for some memory issues due to the new library hence I decided to switch to FiPy

**Comment by tanmoydutta** [comment]
@jmarcelino  thanks for your quick reply. Already tried two different cables. One specially made for chargers. Hence not sure if this is really the case. How else can I find out what is wrong ?

**Comment by jmarcelino** [comment]
Thank you, as a first step please try updating the firmware, the release you have is very old

https://forum.pycom.io/topic/2875/new-firmware-release-v1-17-3-b1

**Comment by tanmoydutta** [comment]
Updated the firmware, still the same problem - 

>>> import os
>>> os.uname()
(sysname='FiPy', nodename='FiPy', release='1.17.3.b1', version='v1.8.6-849-83e2f7f on 2018-03-19', machine='FiPy with ESP32', lorawan='1.0.2', sigfox='1.0.1')
>>>


PYB: soft reboot
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "Pytrack/Pytrack.py", line 5, in <module>
TypeError: cannot create 'module' instances
MicroPython v1.8.6-849-83e2f7f on 2018-03-19; FiPy with ESP32
Type "help()" for more information.
>>>

**Comment by tanmoydutta** [comment]
Conclusion - keep all files in the lib folder without a subfolder.
