### ISSUE TITLE
Libraries libjsmn.a and libsoc.a missing

### ISSUE THREAD

**Issue by robert-hh** [pycom/pycom-micropython-sigfox#16]
These libraries are not included in the repository and are requested during loading.

**Comment by danicampora** [comment]
Should be sorted now with: https://github.com/pycom/pycom-micropython-sigfox/commit/88419a40c0b29d801f3ded6a28f11ebd6aeafaba. 

Thanks @robert-hh !!

**Comment by robert-hh** [comment]
It is. I can build & load.
