### ISSUE TITLE
Documentation for LoRa.preamble invalid

### ISSUE THREAD

**Issue by nevercast** [pycom/pycom-micropython-sigfox#186]
![image](https://user-images.githubusercontent.com/834342/42746391-b53c4d40-892b-11e8-9729-e613f6f9a934.png)

I would expect a preamble instead of a coding constant. 

Kind regards,
Josh.

**Comment by sdaniel55** [comment]
Hi @nevercast 👋 

I think this is a documentation issue, not firmware. If you agree, please open an issue in [pycom/pycom-documentation](https://github.com/pycom/pycom-documentation) and close this one. Thanks!

**Comment by nevercast** [comment]
Sorry, the documentation repo did not exist at the time that I posted this issue. I shall move it.
