### ISSUE TITLE
Pin P8 is never pulled down  if we declare it to

### ISSUE THREAD

**Issue by SeaSlugLabs** [pycom/pycom-micropython-sigfox#19]
I was using WiPy 2.0

Firmware version 
sysname='WiPy', nodename='WiPy', release='1.6.13.b1', version='v1.8.6-607-g9c8a0e9e on 2017-05-01', machine='WiPy with ESP32')

When configuring P8 as input

`p_in = Pin('P8', mode=Pin.IN, pull=Pin.PULL_UP)`  It is high measuring 3.3v

when pulling it down
`p_in = Pin('P8', mode=Pin.IN, pull=Pin.PULL_DOWN)` it stills measure High 3.3V even i declared it as a pull down.

check [pycom forum link](https://forum.pycom.io/topic/1345/p8-as-input-always-high-even-if-pulled-low)

**Comment by danicampora** [comment]
Thanks. Fixed here: https://github.com/pycom/pycom-micropython-sigfox/commit/46f7a10815b4137be02d54799377eb1826bbc4dc
