### ISSUE TITLE
pymakr 2 does not work on linux debian (Mint 19)

### ISSUE THREAD

**Issue by teusH** [pycom/pycom-micropython-sigfox#197]
Installed: pymakr_1.0.0.b1-1_all.deb
Installation was troublesome due to missing libraries and modules (Qt4 versus QT5 problem): pgments, qscintella2, qt4
Solved all those missing dependences.
Running pymakr:
QLabel, QFrame should come from QtWidgets
However QFrame is in many scrips used as an attribute coming from QtGui 
QtGui has no attribute QSizePolicy eg /usr/share/pymakr/modules/QScintilla/Ui_SearchWidget.py", line 31, in setupUi
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
Mixing Qt4 and Qt5 gives lots of troubles ...

Situation info:Version Numbers:
  Python 2.7.15rc1
  Qt 5.9.5
  PyQt 5.10.1
  sip 4.19.7
  QScintilla 2.10.2
  WebKit 602.1
  Pymakr 1.0.0 - beta 1

Platform: linux2
2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
--------------------------------------------------------------------------------
Distribution Info:
  /etc/os-release
  NAME="Linux Mint"
  VERSION="19 (Tara)"
  ID=linuxmint
  ID_LIKE=ubuntu
  PRETTY_NAME="Linux Mint 19"
  VERSION_ID="19"
  HOME_URL="https://www.linuxmint.com/"
  SUPPORT_URL="https://forums.ubuntu.com/"
  BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
  PRIVACY_POLICY_URL="https://www.linuxmint.com/"
  VERSION_CODENAME=tara
  UBUNTU_CODENAME=bionic

  /etc/lsb-release
  DISTRIB_ID=LinuxMint
  DISTRIB_RELEASE=19
  DISTRIB_CODENAME=tara
  DISTRIB_DESCRIPTION="Linux Mint 19 Tara"

This is stopping me using pymakr and halting my MySense project (1 year of development efforts).
Please provide a pymakr which runs ok on Qt5
Thanks
teus hagen

**Comment by sdaniel55** [comment]
Hi @teusH,

Are you using the old Pymakr IDE? It has been discontinued and replaced with the Pymakr plugin for Atom and VSCode. Could you try using one of them with the plugin? Let us know if you're still having issues in [pymakr-atom](https://github.com/pycom/pymakr-atom) or [pymakr-vsc](https://github.com/pycom/pymakr-vsc)
