### ISSUE TITLE
Enhancement - Add uos.statvfs to get flash free space

### ISSUE THREAD

**Issue by pacmac** [pycom/pycom-micropython-sigfox#20]
https://github.com/micropython/micropython/commit/4fb72fe6249ce9f493b5fccc702f875c2c95dd50

Would it be possible to merge this in order to determine the available flash filesystem space ?

Thanks

**Comment by robert-hh** [comment]
uos.getfree() was introduced, which tells the free space of the filesystem.
This issue can therefore be closed.

**Comment by husigeza** [comment]
Hello,
Closing the issue as it is already part of the software.
