### ISSUE TITLE
Lock acquire timeout

### ISSUE THREAD

**Issue by campbellsinclair** [pycom/pycom-micropython-sigfox#207]
Pycom board: WiPy 3.0
Firmware version: (sysname='WiPy', nodename='WiPy', release='1.18.0.r1', version='v1.8.6-849-9569a73 on 2018-07-20', machine='WiPy with ESP32', pybytes='0.9.0')

Steps to cause this issue:
```
import _thread
lock = _thread.allocate_lock()
lock.acquire()
lock.acquire(1, 2.0)
```

I expected the second acquire call to timeout after 2 seconds, but the system did not timeout.

**Comment by campbellsinclair** [comment]
Note: There aren't any tests for this in https://github.com/micropython/micropython/tree/master/tests/thread

**Comment by iwahdan88** [comment]
Timeout argument is not implemented yet
