### ISSUE TITLE
STM LoRa Discovery to LoPy nano gateway

### ISSUE THREAD

**Issue by rajeev1986** [pycom/pycom-micropython-sigfox#210]
We have set up a LoRa gateway using the LoPy module connected to TTN server. For testing, communication from another LoPy acting as end device to LoPy gateway works perfectly and we can receive all the data on the TTN server. However, we would like to use it as a permanent GW for our experiments so that we can connect other LoRa devices, apart from LoPy. 

So we started with STM LoRa discovery kit as an ED. Configured the connection parameters for connecting to the GW. Although we can see the data packets been received by the GW, nothing is seen on the TTN server.  Are we missing something in terms of configuration or data formatting that is prohibiting  LoPy GW to correctly forward the data from STM to TTN?
Does the example provide for the GW is generic and can work with other LoRa devices?

Any suggestions or directions will be welcome.

**Comment by emmanuel-florent** [comment]
Looks like your node pass the GW but to not seen in the (TTN)server.
IMHO LoPy4 LoRa  can work with other LoRa devices.
The node might not have the right configuration (ABP/OTAA, .. ) for joining TTN.
