### ISSUE TITLE
Timeout for Sending AT Commands

### ISSUE THREAD

**Issue by innoagg** [pycom/pycom-micropython-sigfox#215]
1.18.1.r1

GPy, FiPy

LTE.send_at_cmd("")

Would be helpful to be able to set the timeout in micropython so we can execute AT commands that take longer than the 9500ms timeout that is baked into the firmware. There appears to be no work-around since artificially creating a longer wait will risk the AT responses being lost.  A real problem when trying to attach to specific towers or scan for towers.

**Comment by robert-hh** [comment]
That's true. Some commands, like AT+CPOS=?, take very long to respond.

**Comment by iwahdan88** [comment]
Hi @innoagg , this option is available now as per v1.18.1.r6, you can set the parameter `delay` to wait specific amount of time before checking for response from modem on top which the 9500ms timeout is exercisable ... I'll update that in coming releases to just have a configurable timeout.
