### ISSUE TITLE
BLE Write Status Code is Not Returned 

### ISSUE THREAD

**Issue by ansgarstrother** [pycom/pycom-micropython-sigfox#224]
From the documentation: 
```python
characteristic.write(value)
```
Writes the given value on the characteristic. For now it only accepts bytes object representing the value to be written.
```python
characteristic.write(b'x0f')
```
We would like the behavior to be: 
```python
result_code = characteristic.write(value)
```

This is critical to our application since we return specific error codes that are critical to our application.

**Comment by iwahdan88** [comment]
Hello @ansgarstrother thanks for your feedback, I do agree with you , I already created an internal ticket for modifying the BLE module to expose Error codes

**Comment by ansgarstrother** [comment]
@iwahdan88 Was this feature implemented? We are circling back to this project and this feature is critical to our implementation.
