### ISSUE TITLE
GiPy NB-IoT Firmware Upgrade

### ISSUE THREAD

**Issue by wtrocel** [pycom/pycom-micropython-sigfox#230]
Please include the following information when submitting a bug report:

* The Pycom board you are using (e.g. WiPy 2.0, LoPy).
GiPy

* The firmware version you are using. You can get it by executing the following Python code at the REPL:
```
(sysname='GPy', nodename='GPy', release='1.10.1.b1', version='v1.8.6-843-gd3b69c78-dirty on 2017-11-18', machine='GPy with ESP32')
```
The output will look similar to this:
```
File "<stdin>", line 1, in <module>
  File "/flash/lib/sqnsupgrade.py", line 30, in <module>
ImportError: cannot import name LTE

```
* Exact steps to cause this issue
    1. First I did this...
I followed exactly  the SD card firmware upgrade procedure 
    2. Then, I did that...
I tied to import sqnsupgrade as per the instructions

* What you expected
    * a success so I can execute sqnsupgrade.run('/sd/NB1-37781.dup', '/sd/updater.elf') to complete the upgrade to NB-IoT

* What happened instead
I had follwing error below
    File "<stdin>", line 1, in <module>
  File "/flash/lib/sqnsupgrade.py", line 30, in <module>
ImportError: cannot import name LTE

Thank you!

**Comment by iwahdan88** [comment]
Hello @wtrocel LTE class was added as per FW version 1.11.0 and I see you have version 1.10.1.b1 flashed, so please try again after upgrading The esp32 Firmware
