### ISSUE TITLE
flash read err, 1000 on sipy+pytrack

### ISSUE THREAD

**Issue by vinnie38170** [pycom/pycom-micropython-sigfox#240]
I'm using a Sipy on a Pytrack
After a probably failed upgrade I end up with

```
flash read err, 1000
Falling back to built-in command interpreter.
OK
>CWhat?
```

in Atom

I saw some similar problem on this forum, with solutions, but I really don't understand them
and they are all for different chips.

Please, when you ask for "reset" detail what you mean.
I still havent figured out what is what
I know how to press the reset button on my sipy (which does nothing usefull at the moment)
And I know how to pull up the the pin 12 to go back to a better state when you make a mistake. Which is not working anymore

I have no idea how to do that (or if it possible) with the pytrack.

No upload of code possible

I would like to go back to original state so I could start over
Thanks in advance

**Comment by fusspawn** [comment]
I know from other conversations with vinnie38170 on the forums/support this issue was solved and not believed to be an issue with the firmware. Going to close this issue.  

@vinnie38170 Please feel free to reopen or create a new issue if this is still a problem
