### ISSUE TITLE
NB-IoT firmware issues connecting GPy to Orange BE network

### ISSUE THREAD

**Issue by rma-ciss** [pycom/pycom-micropython-sigfox#243]
Hello all,

A few months ago, I successfully connected a GPy module to the Orange network in Belgium and send data to the Maker server of All-Things-Talk. 
At that time the Firmware version I used was NB1-37781. This week, I upgraded the Firmware to NB1-40343 and couldn't attach/connect to the networks any more. I also tried  version NB1-38729, but without success. After backtrack to version NB1-37781, I could again attach/connect to the Orange network.

My question:
- What are the (major) changes between the version NB1-37781 and the later versions? 
- Is there an additional AT-command or setting to be included in the script when using the later FW versions?

My code (works with NB1-37781, but not with later versions):
lte = LTE()
lte.send_at_cmd('AT+CGSN=1') # Get IMEI of module
lte.send_at_cmd('AT+CFUN=0 ') # Turn off Radio
lte.send_at_cmd('AT!="addscanfreq band=20 dl-earfcn=6400" ')
lte.send_at_cmd('AT+CGDCONT=1,"IP","starter.att.iot" ')
lte.send_at_cmd('AT+CEREG=2 ')
lte.send_at_cmd('AT+CFUN=1 ') # Turn on Radio
while not lte.isconnected():
    time.sleep(1)
    pass

Thank you!
Bart

**Comment by Xykon** [comment]
Hello Bart,

The newer NB-IoT firmwares use the same API as for CAT-M1. Please see https://docs.pycom.io/tutorials/lte/nb-iot.html

Regards, Christian

**Comment by rma-ciss** [comment]
Christian,

OK, thx. After flashing the latest version of the FW on the GPy (1.18.1.r7) and with the modem FW NB1-40343 , it works. The GPy connects smoothly to the BEL Orange network!

Bart
