### ISSUE TITLE
NameError: name 'TimeoutError' is not defined

### ISSUE THREAD

**Issue by dbrgn** [pycom/pycom-micropython-sigfox#26]
I'm using the LoPy with firmware 1.7.3.b2.

Some functions like `LoRa.join` raise a `TimeoutError` if something fails. Python [includes](https://docs.python.org/3/library/exceptions.html#TimeoutError) that exception since 3.3.

You define the exception in `py/objexcept.c`:

```c
MP_DEFINE_EXCEPTION(TimeoutError, OSError)
```

I can catch the exception raised by the LoRa class:

```python
>>> try:
...     lora.lora.join(activation=LoRa.OTAA, auth=lora.auth, timeout=1)
... except Exception as ee:
...     foo = ee
...
>>> foo
TimeoutError('timed out',)
>>> foo.__class__
<class 'TimeoutError'>  
```

...but the class does not exist in the global namespace!

```python
>>> TimeoutError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'TimeoutError' is not defined
```

**Comment by husigeza** [comment]
Hello,

Thanks for reporting, the fix will be part of the next development release.
