### ISSUE TITLE
UART.Sendbreak

### ISSUE THREAD

**Issue by Changed-Daily** [pycom/pycom-micropython-sigfox#280]
Pycom board: OEM module W01.
Firmware: (sysname='WiPy', nodename='WiPy', release='1.20.0.rc7', version='v1.9.4-2833cf5 on 2019-02-08', machine='WiPy with ESP32')

Code to reproduce issue: 
```
from machine import UART

#-----------------------------------------------------------------------------------------#

uart = None

#-----------------------------------------------------------------------------------------#

def uart_initialise():

    global uart
    
    if(uart == None):
        uart = UART(1, 57600)
        uart.init(57600, bits=8, parity=None, stop=1)

    return

#-----------------------------------------------------------------------------------------#

def send_break():

    global uart

    if(uart != None):
        uart.sendbreak()

    return
```

Expected output:
First call to uart_initialise() then send_break().
Break sent from UART port when send_break() is called.

Actual output:
When uart.sendbreak() is executed:
TypeError: function takes 2 positional arguments but 1 were given

**Comment by iwahdan88** [comment]
Actually `UART.sendbreak` takes an argument (num of bits duration to hold bus low) for the break condition , however there's still a bug in that function where it does not default to 13 when no parameter is passed as the documentation suggests, we are going to include that update in the next release, but you can get around that by calling `uart.sendbreak(13)`
