### ISSUE TITLE
GPy: No Band8 after update to 1.18.2.r4 or 1.20.0.rc9

### ISSUE THREAD

**Issue by BlackDuck888** [pycom/pycom-micropython-sigfox#285]
Today i did an upgrade for my GPy to the latest revision. 

After that i get for 
```
lte.attach(band=8, apn="iot.1nce.net")
ValueError: band 8 not supported by this board hardware!
```
```
Sysname: GPy
Release: 1.20.0.rc9
Version: v1.9.4-7eeaf3f on 2019-04-01
Machine: GPy with ESP32
Query LTE modem imei... 35434**********
Query SIM iccid... 89882***************
Sent to modem: 'ATI1', delay 1000 ms
UE6.0.0.0
LR6.0.0.0-41019
OK
Sent to modem: 'AT!="showver"', delay 1000 ms
SYSTEM VERSION
==============
  FIRMWARE VERSION
    Bootloader0  : 5.1.1.0 [41065]
    Bootloader1  : 6.0.0.0 [40343]
    Bootloader2* : 6.0.0.0 [41019]
    NV Info      : 1.1,0,0
    Software     : 6.0.0.0 [41019] by robot-soft at 2018-12-13 21:41:15
    UE           : 6.0.0.0
  COMPONENTS
    ZSP0         : 1.0.99-3171
    ZSP1         : 1.0.98-3170
```

But show caps says band 8 is supported

```
Sent to modem: 'AT!="RRC:showcaps"', delay 1000 ms
== CAPS config =============================
  .Lock UE on SRV band    : false
  .MFBI support           : true
  .TM8 TDD support        : false
============================================
== CAPS ====================================
  . access stratum: R13
  . catM          : 1
  . nb-IoT        : 1
-- EUTRA bands --
  . supported     : 66/28/26/25/20/19/18/17/14/13/12/8/5/4/3/2/1
  . board         : 1/2/3/4/5/8/12/13/14/17/18/19/20/25/26/28/66
  . admin         :
  . pending admin :
-- EUTRA carriers --
  . admin         :
  . pending admin :
============================================
```

I never got a connection to lte nb-iot established not on the new firmware or the one before. i have two provider vodafone and 1once. None/nothing worked for me.

**Comment by iwahdan88** [comment]
Hi @BlackDuck888 , what is the hardware version of your GPy , you can find it at the bottom of the board?

**Comment by BlackDuck888** [comment]
GPy V1.0r

**Comment by iwahdan88** [comment]
Yes this version only supports Bands [3, 4, 12, 13, 20, 28]. if you want to use other Bands you have to Submit an [RMA request](https://pycom.io/support-community/support/rma/) for replacement of your board with a new one.

**Comment by BlackDuck888** [comment]
I will, but why they get sold without this support? 
Which Hardwarerevision support this native, for next shopping? 
and last why i don't work with vodafone band 20 ?

**Comment by iwahdan88** [comment]
> I will, but why they get sold without this support?
See this [post](https://forum.pycom.io/topic/3843/important-news-regarding-cat-m1-and-nb-iot-cellular-range) 

> Which Hardware revision support this native, for next shopping?
version 1.2 supports 17 bands with sequanse Firmware 41065(CATM1) and 41019(NB-IOT)

> and last why i don't work with vodafone band 20 ?
v1.0r supports Band 20 , you should not have problem connecting.

Regards

**Comment by BlackDuck888** [comment]
I process the RMA first.

The hardware version should be part of the documentation, i spend near a weak is this without success. an other mail ticket is not anwered/open and show caps shows me that band 8 is supported. 

i had no success, with vodafone and band 20 and i am tring much to get it work.

**Comment by iwahdan88** [comment]
Thanks @BlackDuck888 and sorry for your inconvenience, docs will be updated Asap.
