### ISSUE TITLE
ESP32: Partitioning inconsistency between pycom.io builds and own builds from the repository

### ISSUE THREAD

**Issue by robert-hh** [pycom/pycom-micropython-sigfox#29]
There is obviously an inconsistency in the partition map between firmware builds, made by Pycom and those made locally from the github repository. What happens when:
If you have first loaded an pycom.io firmware via updater tool, and then flash a self built image via "make flash", the device does not start, but just shows a red RGB led. One has to erase the flash completely and reload to get it working.
If you have a self built image working and then load an pycom.io image, the device starts, but the content of the file system is gone.
So: would please someone make these two variants consistent.

**Comment by quentin-ol** [comment]
I'm not sure I'm facing the same core issue but the symptoms are identical.
I build the firmware from GitHub sources and flash using the `make BOARD=xxPY [...] flash` command.
No warning/error during compilation ( after installing a newer IDF as#67 suggested), no error when flashing but resetting the device after removing the G23-GND connection ends up with the RGB LED going red.

**Comment by robert-hh** [comment]
I assume it is solved meanwhile.
