### ISSUE TITLE
Enhancement: Bluetooth should have a timeout function for connect

### ISSUE THREAD

**Issue by kutysam** [pycom/pycom-micropython-sigfox#36]
https://docs.pycom.io/chapter/firmwareapi/pycom/network/bluetooth/

bluetooth.connect(mac_addr)
Opens a BLE connection with the device specified by the mac_addr argument. This function blocks until the connection succeeds or fails. If the connections succeeds it returns a object of type GATTCConnection.
bluetooth.connect('112233eeddff') # mac address is accepted as a string

I have tried putting in a dummy MAC address and it takes 30 seconds to timeout.

I think it will be great if we can set our own timeout.
e.g. bluetooth.connect('MAC',timeout)

**Comment by husigeza** [comment]
Hello,

Thanks for reporting, next development version will contain the requested feature.
