### ISSUE TITLE
Can't post to forum. All posts blocked by Akismet

### ISSUE THREAD

**Issue by askpatrickw** [pycom/pycom-micropython-sigfox#392]
I've tried replying, new post, etc.. Akismet blocks all my posts as spam. This happens with a link, without a link. Nothing works.

Posting here hoping someone can fix it or that an answer can be shared that others can see as well.

thanks!

**Comment by wired8** [comment]
+1

Pycom sort this out!!!!!!  This is a simple setting in the forum config.
