### ISSUE TITLE
WLAN stops responding temporarily for 60 seconds with no error

### ISSUE THREAD

**Issue by dane-if3** [pycom/pycom-micropython-sigfox#406]
(sysname='WiPy', nodename='WiPy', release='1.20.2.rc3-0.8.0-vanilla-squirrel', version='v1.20.2.rc3-4-g4962aea3b-dirty on 2020-02-11', machine='WiPy with ESP32')

I have a machine (WiPy) with an HMI connected via Modbus via WLAN.
(the machine is the modbus server and the HMI is the modbus client, an iphone in this case)
I can start the machine with out HMI connected and ping it for hours.
I can connect the HMI (or several HMI devices) and have it idle and still ping it, possibly less reliably but still good.
(It ends up with the WiPy unresponsive and the heartbeat light solid blue. Different unresolved bug not filed because I have no idea where to begin)
But when I use the machine I get a strange socket failure where the whole WLAN seams to stall  and pause for a minute or so. I say pause because I have seen it reply to the last modbus request sent before the pause when it comes back on line. The HMI modbus client has  abandoned the connection and been trying to reconnect so it doesn't receive the reply.
During this time the WiPy cant be pinged and doesn't reply to ARP requests etc.
Then it comes back to life most of the time and life goes on.
The rest of the machine continues to operate as normal through out the pause. The sockets are checked via select.poll(5) where nothing is returned.
The problem often occurs a short time after pressing continue on the HMI at a certain stage of the machines operation but not always or at the same place in the code and occasionally not at all. After it has happened once it is less likely to happen again until the system is rebooted.

Below is the output from the main loop, and a ping from the computer attached is the pcap
(I think wireshark sees all the duplicate packets due to the way I captured the Wifi at the router)

I started the capture, ping and booted the machine.
once in the main loop I connected the HMI and moved the machine around selected a preset procedure, initiated a reset when it was ready (Reset complete -> ready) 
I pressed continue (Packet number 3730 in the pcap file)
0.06s later the WLAN stopped responding (before the client can send the continue button released) packet 3742
I monitor the time of the last good data from the modbus socket.
this is the number in the line (Active Connections: [[<socket>, 28074]])
if no good data has been received in 1500ms I close the socket
(Connection closed due to inactivity)
the machine continued on with out the WLAN
77s later when it came back packet 3884
I reconnected the HMI and basically did the same thing a second time.
continue button: pcap 8178
this time it ran for 15 seconds before it did the pause thing (around packet 9743)
paused for 60 seconds and back at packet 9923

i have removed all threads, irqs are enabled because poll/sockets dont work if they are disabled
I have tried to comment out code but it doesn't seem to make much difference as the issue occurs at different places or sometimes not at all
Any suggestions on how to narrow this down?
[packet_capture-11.pcap.zip](https://github.com/pycom/pycom-micropython-sigfox/files/4236221/packet_capture-11.pcap.zip)

`INFO:None: Entering Main Loop
Active Connections: []
New connection Client address:('192.168.xxx.xxx', 55593) socket:<socket>
New state: Stopped
program change id:1
New state: Stopped
Continuing to state -3
New state: Resetting
Actuator enabled for reset
New state: Stopped
Active Connections: [[<socket>, 28074]]
program change id:2
New state: Stopped
Continuing to state -3
New state: Resetting
Actuator enabled for reset
long loop 176. Sensor 124, State 4, PID 1, Modbus 31. Sensor times {'f': 116, 'T2': 2, 'Si': 2, 'T1': 2, 'S': 1} 37034
Reset complete -> ready
Active Connections: [[<socket>, 49817]]
Continuing to state 0
New state: Initialiseing
INFO:None: Heater enabled for testing
New state: Home
Connection closed due to inactivity
long loop 163. Sensor 122, State 0, PID 5, Modbus 5. Sensor times {'f': 3, 'T2': 1, 'Si': 2, 'T1': 114, 'S': 1} 60903
Active Connections: []
New state: Tare with drag
New state: Home
New state: Insert test piece
New state: Wait for temperature
long loop 128. Sensor 9, State 1, PID 111, Modbus 5. Sensor times {'f': 3, 'T2': 1, 'Si': 2, 'T1': 2, 'S': 1} 79921
Active Connections: []
long loop 162. Sensor 121, State 1, PID 4, Modbus 5. Sensor times {'f': 3, 'T2': 1, 'Si': 2, 'T1': 2, 'S': 2} 99030
Active Connections: []
long loop 162. Sensor 10, State 0, PID 116, Modbus 5. Sensor times {'f': 3, 'T2': 2, 'Si': 1, 'T1': 2, 'S': 1} 118114
Active Connections: []
long loop 165. Sensor 122, State 1, PID 4, Modbus 5. Sensor times {'f': 115, 'T2': 2, 'Si': 1, 'T1': 1, 'S': 2} 137196
Active Connections: []
New connection Client address:('192.168.xxx.xxx', 55598) socket:<socket>
New state: Stopped
program change id:1
New state: Stopped
Continuing to state -3
New state: Resetting
Actuator enabled for reset
long loop 180. Sensor 10, State 4, PID 2, Modbus 141. Sensor times {'f': 3, 'T2': 2, 'Si': 2, 'T1': 1, 'S': 2} 157766
Active Connections: [[<socket>, 157957]]
New state: Stopped
program change id:2
New state: Stopped
Continuing to state -3
New state: Resetting
Actuator enabled for reset
Reset complete -> ready
Continuing to state 0
New state: Initialiseing
INFO:None: Heater enabled for testing
New state: Home
Active Connections: [[<socket>, 179898]]
long loop 163. Sensor 123, State 0, PID 6, Modbus 6. Sensor times {'f': 115, 'T2': 2, 'Si': 2, 'T1': 2, 'S': 1} 183350
New state: Tare with drag
New state: Home
New state: Insert test piece
INFO:None: USER INPUT REQUIRED
New state: Wait for temperature
New state: Rough touch test piece top
Active Connections: [[<socket>, 200482]]
Connection closed due to inactivity
long loop 167. Sensor 124, State 1, PID 4, Modbus 6. Sensor times {'f': 3, 'T2': 115, 'Si': 2, 'T1': 2, 'S': 1} 202677
Active Connections: []
long loop 163. Sensor 121, State 1, PID 4, Modbus 6. Sensor times {'f': 3, 'T2': 1, 'Si': 2, 'T1': 1, 'S': 112} 221648
Active Connections: []
long loop 164. Sensor 121, State 1, PID 4, Modbus 6. Sensor times {'f': 3, 'T2': 1, 'Si': 2, 'T1': 2, 'S': 1} 240816
Active Connections: []
`

`PING 192.168.xxx.yyy (192.168.xxx.yyy): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
64 bytes from 192.168.xxx.yyy: icmp_seq=4 ttl=255 time=2856.555 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=5 ttl=255 time=1856.865 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=6 ttl=255 time=854.091 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=7 ttl=255 time=4.149 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=8 ttl=255 time=8.797 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=9 ttl=255 time=10.906 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=10 ttl=255 time=5.648 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=11 ttl=255 time=10.814 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=12 ttl=255 time=10.211 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=13 ttl=255 time=5.276 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=14 ttl=255 time=4.559 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=15 ttl=255 time=10.716 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=16 ttl=255 time=5.925 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=17 ttl=255 time=9.763 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=18 ttl=255 time=5.005 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=19 ttl=255 time=7.511 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=20 ttl=255 time=9.441 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=21 ttl=255 time=9.996 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=22 ttl=255 time=3.174 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=23 ttl=255 time=3.742 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=24 ttl=255 time=7.568 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=25 ttl=255 time=3.209 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=26 ttl=255 time=10.847 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=27 ttl=255 time=11.344 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=28 ttl=255 time=5.360 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=29 ttl=255 time=9.592 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=30 ttl=255 time=10.942 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=31 ttl=255 time=9.915 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=32 ttl=255 time=13.434 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=33 ttl=255 time=10.954 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=34 ttl=255 time=10.287 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=35 ttl=255 time=11.584 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=36 ttl=255 time=10.963 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=37 ttl=255 time=10.305 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=38 ttl=255 time=6.046 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=39 ttl=255 time=13.561 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=40 ttl=255 time=12.942 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=41 ttl=255 time=10.034 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=42 ttl=255 time=10.984 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=43 ttl=255 time=8.756 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=44 ttl=255 time=33.635 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=45 ttl=255 time=94.408 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=46 ttl=255 time=75.319 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=47 ttl=255 time=44.722 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=48 ttl=255 time=6.826 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=49 ttl=255 time=9.865 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=50 ttl=255 time=10.994 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=51 ttl=255 time=12.671 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=52 ttl=255 time=3.755 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=53 ttl=255 time=10.400 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=54 ttl=255 time=9.973 ms
Request timeout for icmp_seq 57
Request timeout for icmp_seq 58
Request timeout for icmp_seq 59
Request timeout for icmp_seq 60
Request timeout for icmp_seq 61
Request timeout for icmp_seq 62
Request timeout for icmp_seq 63
Request timeout for icmp_seq 64
Request timeout for icmp_seq 65
Request timeout for icmp_seq 66
Request timeout for icmp_seq 67
Request timeout for icmp_seq 68
Request timeout for icmp_seq 69
Request timeout for icmp_seq 70
Request timeout for icmp_seq 71
Request timeout for icmp_seq 72
Request timeout for icmp_seq 73
Request timeout for icmp_seq 74
Request timeout for icmp_seq 75
Request timeout for icmp_seq 76
Request timeout for icmp_seq 77
Request timeout for icmp_seq 78
Request timeout for icmp_seq 79
Request timeout for icmp_seq 80
Request timeout for icmp_seq 81
Request timeout for icmp_seq 82
Request timeout for icmp_seq 83
Request timeout for icmp_seq 84
Request timeout for icmp_seq 85
Request timeout for icmp_seq 86
Request timeout for icmp_seq 87
Request timeout for icmp_seq 88
Request timeout for icmp_seq 89
Request timeout for icmp_seq 90
Request timeout for icmp_seq 91
Request timeout for icmp_seq 92
Request timeout for icmp_seq 93
Request timeout for icmp_seq 94
Request timeout for icmp_seq 95
Request timeout for icmp_seq 96
Request timeout for icmp_seq 97
Request timeout for icmp_seq 98
Request timeout for icmp_seq 99
Request timeout for icmp_seq 100
Request timeout for icmp_seq 101
Request timeout for icmp_seq 102
Request timeout for icmp_seq 103
Request timeout for icmp_seq 104
Request timeout for icmp_seq 105
Request timeout for icmp_seq 106
Request timeout for icmp_seq 107
Request timeout for icmp_seq 108
Request timeout for icmp_seq 109
Request timeout for icmp_seq 110
Request timeout for icmp_seq 111
Request timeout for icmp_seq 112
Request timeout for icmp_seq 113
Request timeout for icmp_seq 114
Request timeout for icmp_seq 115
Request timeout for icmp_seq 116
Request timeout for icmp_seq 117
Request timeout for icmp_seq 118
Request timeout for icmp_seq 119
Request timeout for icmp_seq 120
Request timeout for icmp_seq 121
Request timeout for icmp_seq 122
Request timeout for icmp_seq 123
Request timeout for icmp_seq 124
Request timeout for icmp_seq 125
Request timeout for icmp_seq 126
Request timeout for icmp_seq 127
Request timeout for icmp_seq 128
Request timeout for icmp_seq 129
Request timeout for icmp_seq 130
Request timeout for icmp_seq 131
Request timeout for icmp_seq 132
64 bytes from 192.168.xxx.yyy: icmp_seq=133 ttl=255 time=95.162 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=134 ttl=255 time=10.798 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=135 ttl=255 time=3.876 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=136 ttl=255 time=11.229 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=137 ttl=255 time=10.348 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=138 ttl=255 time=9.940 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=139 ttl=255 time=13.129 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=140 ttl=255 time=6.866 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=141 ttl=255 time=9.930 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=142 ttl=255 time=4.161 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=143 ttl=255 time=5.802 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=144 ttl=255 time=10.274 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=145 ttl=255 time=5.353 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=146 ttl=255 time=4.642 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=147 ttl=255 time=3.927 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=148 ttl=255 time=3.598 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=149 ttl=255 time=3.932 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=150 ttl=255 time=3.655 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=151 ttl=255 time=3.462 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=152 ttl=255 time=4.827 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=153 ttl=255 time=6.465 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=154 ttl=255 time=4.895 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=155 ttl=255 time=3.955 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=156 ttl=255 time=4.395 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=157 ttl=255 time=4.830 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=158 ttl=255 time=6.450 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=159 ttl=255 time=4.082 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=160 ttl=255 time=4.444 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=161 ttl=255 time=5.182 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=162 ttl=255 time=5.585 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=163 ttl=255 time=5.922 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=164 ttl=255 time=86.635 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=165 ttl=255 time=23.667 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=166 ttl=255 time=124.258 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=167 ttl=255 time=8.710 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=168 ttl=255 time=10.555 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=169 ttl=255 time=5.662 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=170 ttl=255 time=8.157 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=171 ttl=255 time=4.271 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=172 ttl=255 time=3.365 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=173 ttl=255 time=4.124 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=174 ttl=255 time=6.063 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=175 ttl=255 time=3.553 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=176 ttl=255 time=7.184 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=177 ttl=255 time=3.902 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=178 ttl=255 time=4.677 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=179 ttl=255 time=4.462 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=180 ttl=255 time=4.182 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=181 ttl=255 time=4.397 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=182 ttl=255 time=4.713 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=183 ttl=255 time=4.922 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=184 ttl=255 time=3.306 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=185 ttl=255 time=4.616 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=186 ttl=255 time=45.703 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=187 ttl=255 time=10.559 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=188 ttl=255 time=4.358 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=189 ttl=255 time=9.823 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=190 ttl=255 time=3.939 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=191 ttl=255 time=3.847 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=192 ttl=255 time=3.172 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=193 ttl=255 time=3.660 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=194 ttl=255 time=3.118 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=195 ttl=255 time=3.356 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=196 ttl=255 time=5.482 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=197 ttl=255 time=5.056 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=198 ttl=255 time=6.967 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=199 ttl=255 time=3.800 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=200 ttl=255 time=4.081 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=201 ttl=255 time=3.962 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=202 ttl=255 time=4.694 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=203 ttl=255 time=10.006 ms
Request timeout for icmp_seq 204
Request timeout for icmp_seq 205
Request timeout for icmp_seq 206
Request timeout for icmp_seq 207
Request timeout for icmp_seq 208
Request timeout for icmp_seq 209
Request timeout for icmp_seq 210
Request timeout for icmp_seq 211
Request timeout for icmp_seq 212
Request timeout for icmp_seq 213
Request timeout for icmp_seq 214
Request timeout for icmp_seq 215
Request timeout for icmp_seq 216
Request timeout for icmp_seq 217
Request timeout for icmp_seq 218
Request timeout for icmp_seq 219
Request timeout for icmp_seq 220
Request timeout for icmp_seq 221
Request timeout for icmp_seq 222
Request timeout for icmp_seq 223
Request timeout for icmp_seq 224
Request timeout for icmp_seq 225
Request timeout for icmp_seq 226
Request timeout for icmp_seq 227
Request timeout for icmp_seq 228
Request timeout for icmp_seq 229
Request timeout for icmp_seq 230
Request timeout for icmp_seq 231
Request timeout for icmp_seq 232
Request timeout for icmp_seq 233
Request timeout for icmp_seq 234
Request timeout for icmp_seq 235
Request timeout for icmp_seq 236
Request timeout for icmp_seq 237
Request timeout for icmp_seq 238
Request timeout for icmp_seq 239
Request timeout for icmp_seq 240
Request timeout for icmp_seq 241
Request timeout for icmp_seq 242
Request timeout for icmp_seq 243
Request timeout for icmp_seq 244
Request timeout for icmp_seq 245
Request timeout for icmp_seq 246
Request timeout for icmp_seq 247
Request timeout for icmp_seq 248
Request timeout for icmp_seq 249
Request timeout for icmp_seq 250
Request timeout for icmp_seq 251
Request timeout for icmp_seq 252
64 bytes from 192.168.xxx.yyy: icmp_seq=253 ttl=255 time=40.630 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=254 ttl=255 time=10.409 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=255 ttl=255 time=4.655 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=256 ttl=255 time=4.299 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=257 ttl=255 time=11.857 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=258 ttl=255 time=12.307 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=259 ttl=255 time=9.880 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=260 ttl=255 time=11.690 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=261 ttl=255 time=4.166 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=262 ttl=255 time=9.971 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=263 ttl=255 time=12.119 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=264 ttl=255 time=10.419 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=265 ttl=255 time=8.945 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=266 ttl=255 time=9.958 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=267 ttl=255 time=5.054 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=268 ttl=255 time=9.526 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=269 ttl=255 time=10.644 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=270 ttl=255 time=10.467 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=271 ttl=255 time=6.425 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=272 ttl=255 time=10.861 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=273 ttl=255 time=4.020 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=274 ttl=255 time=16.448 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=275 ttl=255 time=9.256 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=276 ttl=255 time=10.525 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=277 ttl=255 time=10.080 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=278 ttl=255 time=10.306 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=279 ttl=255 time=4.124 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=280 ttl=255 time=8.436 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=281 ttl=255 time=9.219 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=282 ttl=255 time=11.398 ms
64 bytes from 192.168.xxx.yyy: icmp_seq=283 ttl=255 time=9.051 ms
^C
--- 192.168.xxx.yyy ping statistics ---
284 packets transmitted, 153 packets received, 46.1% packet loss
round-trip min/avg/max/stddev = 3.118/47.540/2856.555/280.694 ms
`

**Comment by robert-hh** [comment]
I made the same experience of WiFi practically unresponsive, if my Python code would execute in a thigh busy loop. Adding a short time.sleep_ms(delay) imroved the behavior significantly.  The value for delay can be as small as 1. What happens is, that on calling any of the sleep functions, pending tasks are scheduled.

**Comment by amotl** [comment]
@robert-hh: Would it also work just using `time.sleep_ms(0)` in order to yield to the scheduler?

**Comment by robert-hh** [comment]
@amotl That#s hard to tell. sleep_ms() calls mp_hal_delay_ms() calls vTaskDelay() without checking the value of the argument. So it's up to testing. But idle() may have the same effect, which just calls taskYIELD().

**Comment by dane-if3** [comment]
@robert-hh Sorry I didn't include the code for the loop. (see below)
I use sleep_ms to force the loop to run at 50ms or more to be sure the external ADC is ready with a new value.
But even if the last loop was longer than 50ms I still sleep for 1ms (I had sockets in threads and it worked better with several short sleeps. I didn't change this when I swapped the threaded sockets to select.poll() sockets in the main thread)

The main difference before and after pressing continue is a small amount of code calculating PIDs to set the duty cycles for both PWMs and the PWMs are both running
Both PWM can be running with no problem I am not saying they are the issue.


`try:
    while not E_Stop():
        #wdt.feed()
        ### Don't cycle quicker than the minimum loop time.
        t = utime.ticks_ms()
        looptime_period = utime.ticks_diff(t,looptime_last)
        looptime_last = t
        if looptime_period > 2*looptime_min:
            print('long loop {}. Sensor {}, State {}, PID {}, Modbus {}. Sensor times {} {}'.format(looptime_period, sensorUpdateTime,stateUpdateTime,pidUpdateTime,ModbusUpdateTime, test_machine.sensors.ts, t))
        utime.sleep_ms(max(1,looptime_min-looptime_period))

        irq_state=machine.disable_irq()
        ### Update the sensor data
        sensorUpdateTime=-utime.ticks_ms()
        with a_lock:  #print("a_lock is locked while this executes")
            test_machine.sensors.update() # will throw a hard limit error finally can sort it out at the momnet need to handle this proprerly
        sensorUpdateTime+=utime.ticks_ms()

        ### Update/Run the active state
        stateUpdateTime=-utime.ticks_ms()
        if not procedure_manager.runningPocedure.update_state(): break
        stateUpdateTime+=utime.ticks_ms()

        ### Update the controllers
        pidUpdateTime=-utime.ticks_ms()
        test_machine.heater.update()
        test_machine.actuator.update()
        pidUpdateTime+=utime.ticks_ms()
        machine.enable_irq(irq_state)

        ### Output Modbus data
        ModbusUpdateTime=-utime.ticks_ms()
        server.poll(5)
        ModbusUpdateTime+=utime.ticks_ms()

        if i % 500==0:
            print('Active Connections:',server.active_connections)
        i=i+1
`

**Comment by dane-if3** [comment]
This is mostly a problem caused by me.
Pycom development boards use pin 12 to switch between the internal and external wifi antennas. 
This can also be done with WLAN.init( ... antenna=WLAN.INT_ANT) which is the only way to do it on the OEM versions of the device. 
On the expansion board Pin 12 is also Pin.exp_board.G28 which is the pin I used for the PWM channel for the heater PID controller.
While the temperature is close to the setpoint the duty cycle is set to zero or close enough to zero to not effect the wifi. If the temperature drops, door opened or machine stopped for a while, the duty cycle increases and the wifi started switching to the external non connected antenna for long enough periods that packets and retransmissions were missed.
So the randomness of this and the G28 pin made it harder to realise I had not read the manual correctly...
It would be nice to have an exception alerting the user that it is a bad idea to use the pin when wifi is enabled. I cant see that this is practical to implement.
