### ISSUE TITLE
Size of large files is displayed wrong

### ISSUE THREAD

**Issue by robert-hh** [pycom/pycom-micropython-sigfox#43]
All versions:
for files larger than 2 GB the file size is displayed as negative number, resulting from a int <-> uint mismatch in the code for uos.stat(). This can be fixed by changing line 436 of mods/moduos.c into:
```
    t->items[6] = mp_obj_new_int_from_uint(fno.fsize); // st_size
```
Nothing tragic.

**Comment by danicampora** [comment]
@robert-hh thanks!
