### ISSUE TITLE
[HELP] Tagging the repository

### ISSUE THREAD

**Issue by amotl** [pycom/pycom-micropython-sigfox#457]
Dear @geza-pycom, @peter-pycom, @mate-pycom, @catalinio, @salal-m and @Xykon,

thanks a bunch for picking up the work on the code base and for sharing your efforts with the community. We are looking forward to test the updates, specifically since #418 (plus adjustments) and #413 have been merged.

Saying that, we recognize v1.20.2.rc7 has rolled by and you are now aiming at v1.20.2.rc9, as 63d7be95 suggests. May we humbly ask you to start pushing respective tags to the repository again for the sake of completeness? That will tremendously help all people following the development.

Thanks already and with kind regards,
Andreas.

**Comment by peter-pycom** [comment]
Hey @amotl 

thanks again to you for your help with those!

Apologies for the delays with the tags. It should be sorted now.

Regards
Peter

**Comment by amotl** [comment]
Thanks a bunch!
