### ISSUE TITLE
False value returned by lora.stats()

### ISSUE THREAD

**Issue by ha5di** [pycom/pycom-micropython-sigfox#48]
Board: LoPy

Firmware: 1.7.8.b1

snr returned by lora.stats() is not the snr in dB but the value returned by LoRa HAL. It must devided by 4.

Forum reference: https://forum.pycom.io/topic/1597/false-value-returned-by-lora-stats

**Comment by ha5di** [comment]
One notice. Would be good to get a single precision float instead of integer not to loose precision.

**Comment by danicampora** [comment]
Fixed. Thanks!
