### ISSUE TITLE
pycom-esp-idf/components/openthread not found

### ISSUE THREAD

**Issue by x893** [pycom/pycom-micropython-sigfox#481]
Hi,
i add  OPENTHREAD=on to make and see
`
In file included from mods/modlora.c:61:0:
mods/modmesh.h:28:33: fatal error: openthread/instance.h: No such file or directory
compilation terminated.

In file included from mods/modmesh.c:10:0:
mods/modmesh.h:28:33: fatal error: openthread/instance.h: No such file or directory
compilation terminated.
`
Can you help me to resolve this issue ?

Thanks in advance

**Comment by peter-pycom** [comment]
Sorry, no. The openthread integration is not publicly available
