### ISSUE TITLE
LoRaWAN - Return downlink destination port

### ISSUE THREAD

**Issue by ha5di** [pycom/pycom-micropython-sigfox#49]
Board: LoPy

Firmware: 1.7.8.b1

Please make available destination port of LoRaWAN downlink messages for user space.

Forum reference: https://forum.pycom.io/topic/1582/lorawan-return-downlink-destination-port

**Comment by danicampora** [comment]
Fixed. Thanks!

**Comment by danicampora** [comment]
Added recvfrom() method.
