### ISSUE TITLE
LoPy-4 firmware 1.20.2.rc13 LoRa init hangup

### ISSUE THREAD

**Issue by teusH** [pycom/pycom-micropython-sigfox#513]
LoPy-4 with firmware release 1.20.2.rc13 (July 2020):
>>> from network import LoRa
>>> lora = LoRa(mode=LoRa.LORAWAN, region=LoRa.EU868)
It hangs after 1 minute the LoRa class object load fails and ends in a soft reboot
Back to 1.20.2.r3:
>>> from network import LoRa
>>> lora = LoRa(mode=LoRa.LORAWAN, region=LoRa.EU868)
>>>
No problem and e.g. a LoRa join() succeeds.

**Comment by gijsio** [comment]
I understand the issue, but we are not working at improving older firmwares (ie. 1.20.2.r3 is newer than 1.20.2.rc13)

**Comment by peter-pycom** [comment]
Indeed, r3 is the release that came after rc13 that fixed the issue.
