### ISSUE TITLE
VSCode Pymakr  command 'pymakr.upload' not found

### ISSUE THREAD

**Issue by antifm** [pycom/pycom-micropython-sigfox#529]
![issue](https://user-images.githubusercontent.com/51391083/106969997-1a622500-67a0-11eb-89b3-5b0b25156867.png)
![Screenshot 2021-02-05 104747](https://user-images.githubusercontent.com/51391083/106970039-2b129b00-67a0-11eb-8923-0e5cb982fb60.png)

Recently VScode has updated to version 1.53 and using the Pymakr extension v1.1.7 no longer works. Pymakr no longer starts up upon VScode opening and Run/Upload commands also do not work. 

I tried disconnecting FiPy and reconnecting it in the attempt of forcing a terminal to pop up where it connects, however, no response was found. 

I've attached two images indicating how the bottom-left Pymakr button is missing and the responses were given when pressing run/upload buttons. Additionally, I've attached how Pymakr is missing from the terminal as an option.

Will there be an update soon in response to the new VScode update?

Thanks

**Comment by elmasria** [comment]
Hi @antifm 

Thank you for reporting this. we will fix this issue and upload a new version of Pymakr 

Best Regards,
Ahmad EL Masri

**Comment by peter-pycom** [comment]
Fixed version has been released
