### ISSUE TITLE
Pybytes message sent to GCP is base64, how do I change that?

### ISSUE THREAD

**Issue by malza037** [pycom/pycom-micropython-sigfox#535]
* The Pycom board you are using Fipy
* The firmware version you are using FW1.20.2.R4
```
This is the data I am getting from Atom
![pybytes 3-11-21](https://user-images.githubusercontent.com/80499717/110885706-56b00600-82b5-11eb-8b2b-d3e3be6c60eb.JPG)

This is the data GCP is receiving
![GCP 3-11-21](https://user-images.githubusercontent.com/80499717/110885899-abec1780-82b5-11eb-9fd2-13c14dbd47c6.JPG)

Please I need help ASAP. This is for my final Engineering design project, so I can graduate.

**Comment by gijsio** [comment]
This issue was solvedin the meantime. Google Cloud Platform does not natively support the data64 through the pybytes integration. Instead, it is possible to use a webhook to connect through a diy webservice and read the floating point value there.
