### ISSUE TITLE
int.from_bytes(b'\xFF\x00','big') returns incorrect result

### ISSUE THREAD

**Issue by bboser** [pycom/pycom-micropython-sigfox#55]
Hardware: WiPy 2.0 (though probably same issue on all).

Problem: int.from_bytes(b'\xFF\x00','big')
returns 255. Expected: 65280 for big endian (255 is correct for little endian).

Apparently this was fixed in the original micropython.org branch in January with PR #2791.

**Comment by sdaniel55** [comment]
Tested on version `1.18.1.r1`, it returned `65280`.
