### ISSUE TITLE
Firmware Update Fail, failed to create record

### ISSUE THREAD

**Issue by ghost** [pycom/pycom-micropython-sigfox#553]
I have new(ish) Fipy boards with Pysense expansion boards,

Tried to update the firmware using the updater tool on Windows.  This connects ok on com port.

The update tool proceeds until it starts the flash, see image
![Screenshot 2021-05-18 120155](https://user-images.githubusercontent.com/22086010/118570762-e8198800-b7d0-11eb-9e4b-30194361d0da.png)

update tool release is 1.16.5

I had the same issue when trying a different expansion board that I know does work.  I have a Lopy that does flash ok on this.

I was able to do a manual update using FiPy-1.20.2.r4.tar
But I'm not sure what region settings this results in for the Sigfox and Lora modules.

TIA.

**Comment by Xykon** [comment]
Sorry this should be fixed now.

**Comment by ghost** [comment]
Thanks Christian.  The units seem ok on the manual install.  I'll check them out over next few days as we get going.
