### ISSUE TITLE
Atom editor crashes when trying to connect to Pycom

### ISSUE THREAD

**Issue by lesure1** [pycom/pycom-micropython-sigfox#72]
Hello,

I am trying to connect to Pycom (1.1.3) from Atom editor (Atom: 1.20.1, Electron: 1.6.9, Chrome: 56.0.2924.87, Node: 7.4.0) on Ubuntu 14.04. I added Pymkr 1.1.3 automatically using the Atom GUI. The Atom editor crashes when clicking on connect, after retrieving and setting the USB serial port for Pycom. The message displayed is "Editor has crashed. Please report this issue". I am totally new to the environment and trying to do my first set up. Could anyone help me identify the source of the problem and fix it?

Thank you!

**Comment by robert-hh** [comment]
The questions around pymakr & atom are discussed here in detail: https://forum.pycom.io/topic/1026/pymakr-atom-plugin-released/68

**Comment by lesure1** [comment]
Okay, thanks. I will post it there.

**Comment by sdaniel55** [comment]
I'll close this issue because it has not had any recent activity. Thank you for your contributions!
