### ISSUE TITLE
Making mpy-cross  is failing  1.9.0

### ISSUE THREAD

**Issue by syndycat** [pycom/pycom-micropython-sigfox#76]
1. I did a Fresh new git pull and submodules update
     pycom-esp-idf.git
     pycom-micropython-sigfox 

Then: 
                    **$ cd mpy-cross
                    $ make all**

Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosit                                                                                                                                                                                               y.
mkdir -p build/genhdr
Generating build/genhdr/mpversion.h
GEN build/genhdr/qstr.i.last
GEN build/genhdr/qstr.split
GEN build/genhdr/qstrdefs.collected.h
QSTR updated
GEN build/genhdr/qstrdefs.generated.h
mkdir -p build/py/
mkdir -p build/py/../extmod/
mkdir -p build/py/../lib/embed/
mkdir -p build/py/../lib/utils/
mkdir -p build/windows/
CC ../py/mpstate.c
CC ../py/nlrx86.S
CC ../py/nlrx64.S
CC ../py/nlrthumb.c
CC ../py/nlrxtensa.S
CC ../py/nlrsetjmp.c
CC ../py/malloc.c
CC ../py/gc.c
CC ../py/qstr.c
CC ../py/vstr.c
CC ../py/mpprint.c
CC ../py/unicode.c
CC ../py/mpz.c
CC ../py/lexer.c
CC ../py/lexerstr.c
CC ../py/lexerunix.c
CC ../py/parse.c
CC ../py/scope.c
CC ../py/compile.c
CC ../py/emitcommon.c
CC ../py/emitbc.c
CC ../py/asmx64.c
CC ../py/emitnative.c
CC ../py/asmx86.c
CC ../py/emitnative.c
CC ../py/asmthumb.c
CC ../py/emitnative.c
CC ../py/emitinlinethumb.c
CC ../py/asmarm.c
CC ../py/emitnative.c
CC ../py/formatfloat.c
CC ../py/parsenumbase.c
CC ../py/parsenum.c
CC ../py/emitglue.c
CC ../py/runtime.c
CC ../py/runtime_utils.c
CC ../py/nativeglue.c
CC ../py/stackctrl.c
CC ../py/argcheck.c
CC ../py/warning.c
CC ../py/map.c
CC ../py/obj.c
CC ../py/objarray.c
CC ../py/objattrtuple.c
CC ../py/objbool.c
CC ../py/objboundmeth.c
CC ../py/objcell.c
CC ../py/objclosure.c
CC ../py/objcomplex.c
CC ../py/objdict.c
CC ../py/objenumerate.c
CC ../py/objexcept.c
CC ../py/objfilter.c
CC ../py/objfloat.c
CC ../py/objfun.c
CC ../py/objgenerator.c
CC ../py/objgetitemiter.c
CC ../py/objint.c
CC ../py/objint_longlong.c
CC ../py/objint_mpz.c
CC ../py/objlist.c
CC ../py/objmap.c
CC ../py/objmodule.c
CC ../py/objobject.c
CC ../py/objpolyiter.c
CC ../py/objproperty.c
CC ../py/objnone.c
CC ../py/objnamedtuple.c
CC ../py/objrange.c
CC ../py/objreversed.c
CC ../py/objset.c
CC ../py/objsingleton.c
CC ../py/objslice.c
CC ../py/objstr.c
CC ../py/objstrunicode.c
CC ../py/objstringio.c
CC ../py/objtuple.c
CC ../py/objtype.c
CC ../py/objzip.c
CC ../py/opmethods.c
CC ../py/sequence.c
CC ../py/stream.c
CC ../py/binary.c
CC ../py/builtinimport.c
CC ../py/builtinevex.c
CC ../py/modarray.c
CC ../py/modbuiltins.c
CC ../py/modcollections.c
CC ../py/modgc.c
CC ../py/modio.c
CC ../py/modmath.c
CC ../py/modcmath.c
CC ../py/modmicropython.c
CC ../py/modstruct.c
CC ../py/modsys.c
CC ../py/moduerrno.c
CC ../py/modthread.c
CC ../py/vm.c
CC ../py/bc.c
CC ../py/showbc.c
CC ../py/repl.c
CC ../py/smallint.c
CC ../py/frozenmod.c
CC ../py/../extmod/moductypes.c
CC ../py/../extmod/modujson.c
CC ../py/../extmod/modure.c
CC ../py/../extmod/moduzlib.c
CC ../py/../extmod/moduheapq.c
CC ../py/../extmod/moduhashlib.c
CC ../py/../extmod/modubinascii.c
CC ../py/../extmod/virtpin.c
CC ../py/../extmod/machine_mem.c
CC ../py/../extmod/machine_pinbase.c
CC ../py/../extmod/machine_pulse.c
CC ../py/../extmod/machine_i2c.c
CC ../py/../extmod/machine_spi.c
CC ../py/../extmod/modussl_axtls.c
CC ../py/../extmod/modussl_mbedtls.c
CC ../py/../extmod/modurandom.c
CC ../py/../extmod/modwebsocket.c
CC ../py/../extmod/modwebrepl.c
CC ../py/../extmod/modframebuf.c
CC ../py/../extmod/fsusermount.c
CC ../py/../extmod/vfs_fat.c
CC ../py/../extmod/vfs_fat_ffconf.c
CC ../py/../extmod/vfs_fat_diskio.c
CC ../py/../extmod/vfs_fat_file.c
CC ../py/../extmod/vfs_fat_lexer.c
CC ../py/../extmod/vfs_fat_misc.c
CC ../py/../extmod/utime_mphal.c
CC ../py/../extmod/uos_dupterm.c
CC ../py/../lib/embed/abort_.c
CC ../py/../lib/utils/printf.c
CC main.c
CC gccollect.c
CC ../windows/fmode.c
../windows/fmode.c: In function ‘set_fmode_impl’:
../windows/fmode.c:36:5: error: ‘_fmode’ undeclared (first use in this function)
     _fmode = mode;
     ^~~~~~
../windows/fmode.c:36:5: note: each undeclared identifier is reported only once for each function it appears in
make: *** [../py/mkrules.mk:47: build/windows/fmode.o] Error 1

**Comment by Xykon** [comment]
Hello, please see this link for a solution: https://github.com/micropython/micropython/issues/2298

I will see if we can get this fixed in the next release.

**Comment by Xykon** [comment]
This should now be fixed. Can you please check to confirm?

**Comment by sdaniel55** [comment]
Hi @syndycat 👋 
I'll close this issue because it has not had any recent activity and should be resolved. Thank you for your contributions!
