### ISSUE TITLE
Error building image for esp32

### ISSUE THREAD

**Issue by jingai** [pycom/pycom-micropython-sigfox#83]
Everything compiles fine until it goes to build the image:

```
% cd esp32
% make BOARD=LOPY LORA_BAND=USE_BAND_915 TARGET=app
[snipped]
Building partitions from lib/partitions.csv...
IMAGE build/LOPY_915/release/lopy_915.bin
esptool.py v2.0.1

A fatal error occurred: Segment loaded at 0x401b274c lands in same 64KB flash mapping as segment loaded at 0x401b2734. Can't generate binary. Suggest changing linker script or ELF to merge sections.
application.mk:371: recipe for target 'build/LOPY_915/release/lopy_915.bin' failed
```

**Comment by robert-hh** [comment]
This is recently a common problem with the extensa gcc compiler. You have to use an older version of the compiler. See this discussion with links at the end: https://forum.pycom.io/topic/1429/solved-having-issues-build-firmware-from-soure

**Comment by virtualguy** [comment]
Using the correct compiler for a given firmware seems to be a recurring
issue. Would adding a check / warning to the makefile be worthwhile? There
are already similar checks for the esp-idf and would ensure consistent
results for users  which is especially important as the compiler is
changing a lot.

**Comment by jingai** [comment]
@robert-hh thanks, but that doesn't seem to solve my particular issue.  I've installed the version of the compiler referenced in that post and still get:

```
IMAGE build/LOPY_915/release/lopy_915.bin
esptool.py v2.0.1

A fatal error occurred: Segment loaded at 0x401b274c lands in same 64KB flash mapping as segment loaded at 0x401b2734. Can't generate binary. Suggest changing linker script or ELF to merge sections.
application.mk:371: recipe for target 'build/LOPY_915/release/lopy_915.bin' failed
```

**Comment by robert-hh** [comment]
Which version of the C-Compiler are you actually using?

**Comment by jingai** [comment]
I managed to get it to build with 1.22.0-61-gab8375a.  Thanks again.

**Comment by Xykon** [comment]
I have pushed a new version of README.md to reflect the correct compiler version... closing this issue.
